environments:
  dev:
    values:
      - environments/dev.yaml
  prod:
    values:
      - environments/prod.yaml

---

releases:
  - name: logistics-pickup
    namespace: logistics-{{ .Environment.Name }}
    createNamespace: true
    chart: ./charts/logistics-pickup
    values:
      - charts/logistics-pickup/values.yaml
    set:
      - name: image.tag
        value: {{ .Values.pickup.tag }}
      - name: replicaCount
        value: {{ .Values.pickup.replicaCount }}
      - name: env.APP_ENV
        value: {{ .Values.appEnv }}

  - name: logistics-delivery
    namespace: logistics-{{ .Environment.Name }}
    createNamespace: true
    chart: ./charts/logistics-delivery
    values:
      - charts/logistics-delivery/values.yaml
    set:
      - name: image.tag
        value: {{ .Values.delivery.tag }}
      - name: replicaCount
        value: {{ .Values.delivery.replicaCount }}
      - name: env.APP_ENV
        value: {{ .Values.appEnv }}