# environments/dev.yaml
# Auto-updated by GitHub Actions CI via devops-central

appEnv: development

pickup:
  tag: dev-4f60ec3
  replicaCount: 1

delivery:
  tag: dev-3e3c0dd
  replicaCount: 1

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
